server:
  port: 8083

spring:
  application:
    name: RATING-SERVICE

  config:
    import: optional:configserver:http://localhost:8086

  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#      to establish a kafka producer envirnment
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer




okta:
  oauth2:
    issuer: https://dev-87721458.okta.com/oauth2/default
    audience: api://default


#  spring.kafka.producer.bootstrap-servers = localhost:9092
#  spring.kafka.producer.key-serializer = org.apache.kafka.common.serialization.StringSerializer
#  spring.kafka.producer.value-serializer = org.apache.kafka.common.serialization.StringSerializer


#  eureka:
#    instance:
#      prefer-ip-address: true
#    client:
#      fetch-registry: true
#      register-with-eureka: true
#      service-url:
#        defaultZone: http://localhost:8761/eureka
