server:
  port: 8084

spring:
  application:
    name: API-GATEWAY


  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/api/hotels/**



        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/api/ratings/**

  config:
    import: optional:configserver:http://localhost:8086


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka



okta:
  oauth2:
    issuer: https://dev-87721458.okta.com/oauth2/default
    audience: api://default
    client-id: 0oabiefu1z9pvqMcB5d7
    client-secret: GHVtQF7koiWfNR6hQ5R2_y1-nliCWbrJLjGBJGmYAMVigA8NS_VyIL6HB7UQI81I
    scopes: openid, profile, email, offline_access


