server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



  config:
    import: optional:configserver:http://localhost:8086
#  eureka:
#    instance:
#      prefer-ip-address: true
#    client:
#      fetch-registry: true
#      register-with-eureka: true
#      service-url:
#        defaultZone: http://localhost:8761/eureka

#  security:
#    oauth2:
#     resourceserver:
#        jwt:
#        issuer-uri: https://dev-87721458.okta.com/oauth2/default
#    client:
#      registration:
#        my-internal-client:
#          provider: okta
#          authorization-grant-type: client_credentials
#          scope: internal
#          client-id: 0oabiefu1z9pvqMcB5d7
#          client-secret: GHVtQF7koiWfNR6hQ5R2_y1-nliCWbrJLjGBJGmYAMVigA8NS_VyIL6HB7UQI81I
#      provider:
#        okta:
#          issuer-uri: https://dev-87721458.okta.com/oauth2/default



  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  https://dev-87721458.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oabiefu1z9pvqMcB5d7
            client-secret: GHVtQF7koiWfNR6hQ5R2_y1-nliCWbrJLjGBJGmYAMVigA8NS_VyIL6HB7UQI8

        provider:
          okta:
            issuer-uri:  https://dev-87721458.okta.com/oauth2/default

#kafka consumer envirment
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer



#circuit breaker for the ressiliance 4j springboot 2
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always



  resilience4j:
    circuitbreaker:
      instances:
        Chandrayana:
          registerHealthIndicator: true
          eventConsumerBufferSize: 10
          failureRateThreshold: 50
          minimumNumberOfCalls: 5
          automaticTransitionFromOpenToHalfOpenEnabled: true
          waitDurationInOpenState: 6s
          permittedNumberOfCallsInHalfOpenState: 3
          slidingWindowSize: 10
          slidingWindowType: COUNT_BASED


#circuitBreaker for the Retry module

#  retry:
#    instances:
#      Chandrayana:
#        max-attempts: 3
#        wait-duration: 5s

#circuit breaker as a RateLimiter

#  ratelimiter:
#    instances:
#      userRateLimiter:
#        limit-refresh-period: 4s
#        limit-for-period: 2
#        timeout-duration: 2s

okta:
  oauth2:
    issuer: https://dev-87721458.okta.com/oauth2/default
    audience: api://default


#    kafka consumer envirnment
#  spring.kafka.consumer.bootstrap-servers = localhost:9092
#  spring.kafka.consumer.group-id= group-1
#  spring.kafka.consumer.auto-offset-reset = earliest
#  spring.kafka.consumer.key-deserializer= org.apache.kafka.common.serialization.StringDeserializer
#  spring.kafka.consumer.value-deserializer = org.apache.kafka.common.serialization.StringDeserializer
#  server.port=9090